name: Deploy documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    container:
      image: node:slim
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: ./build
          retention-days: 1

  deploy-stage:
    needs: build
    runs-on: self-hosted
    container:
      image: node:slim
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: web-build
          path: ./build

      - uses: ./.github/workflows/install-aws-cli

      - name: Deploy to stage
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 sync --acl public-read --delete ./build/ s3://${{ vars.S3_BUCKET }}-stage/

  deploy-prod:
    needs: build
    runs-on: self-hosted
    container:
      image: node:slim
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: web-build
          path: ./build

      - uses: ./.github/workflows/install-aws-cli

      - name: Deploy to prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 sync --acl public-read --delete ./build/ s3://${{ vars.S3_BUCKET }}-prod/
